// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  devtools: { enabled: import.meta.dev },
  ssr: true,

  modules: [
    '@nuxtjs/tailwindcss',
    '@nuxtjs/google-fonts',
  ],

  googleFonts: {
    families: {
      'Cormorant Garamond': [300, 400, 500],
      Inter: [300, 400, 500],
      'IBM Plex Mono': [400, 500],
    },
    display: 'swap',
    // Self-host the fonts (downloaded to /public/fonts + /public/css/nuxt-google-fonts.css)
    // so they work on every device instead of relying on locally installed system fonts.
    download: true,
    inject: false, // we inject the generated stylesheet manually below (reliable under prerender)
    overwriting: true,
    outputDir: 'public',
    stylePath: 'css/nuxt-google-fonts.css',
    fontsDir: 'fonts',
    preload: false,
    prefetch: false,
  },

  app: {
    head: {
      title: 'Digital Zen | Portfolio',
      meta: [
        { name: 'description', content: 'Crafting Digital Serenity - A minimalist portfolio experience' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'theme-color', content: '#F5F5F3' },
      ],
      htmlAttrs: {
        lang: 'en',
      },
      link: [
        // Self-hosted Latin fonts (Cormorant Garamond / Inter / IBM Plex Mono),
        // generated by @nuxtjs/google-fonts (download: true). Linked explicitly so it is
        // always present in the prerendered HTML on every device.
        { rel: 'stylesheet', href: '/css/nuxt-google-fonts.css' },
        // CJK fallbacks (Noto Serif TC / Noto Sans TC) are loaded via @import in
        // assets/css/main.css — the google-fonts module hijacks googleapis stylesheet
        // <link> tags in head, so a CSS @import is used instead. preconnect speeds it up.
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
      ],
    },
  },

  css: ['~/assets/css/main.css'],

  routeRules: {
    '/': { prerender: true },
    '/**': { prerender: true },
  },

  nitro: {
    prerender: {
      crawlLinks: true,
      routes: ['/'],
    },
  },

  vite: {
    build: {
      cssCodeSplit: true,
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (id.includes('node_modules/gsap')) return 'gsap'
          },
        },
      },
    },
  },

  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
})
